
server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

customer:
  service:
    url: http://localhost:8084

auth:
  service:
    url: http://localhost:8080
    username: admin@entelect.co.za
    password: password

jwt:
  secret: mySuperSecretKey1234567890123456789012345678901234567890
  expiration: 86400000